### ISSUE TITLE
 [Question] seekbar preview like web version

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android#502]
Hello
i was wondering if there is a way to support preview video while seeking as in the web player version

thanks

**Comment by kaltura-hooks** [comment]
Hi @oahmedazab,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by oahmedazab** [comment]
Hello

> Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
> please provide as much details as possible.
- in web version of the player user can preview video frames while seeking i was wondering if the same behavior supported in android version

> Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
-  i am using Kaltura VPAAS

**Comment by giladna** [comment]
@oahmedazab 

there is API to download an image using this API
you have to use your partnerId and the mediaId you want to preview
you can change the width and the num of slices as you wish

https://cdnapisec.kaltura.com/p/2222401/sp/222240100/thumbnail/entry_id/1_f93tepsn/width/519/vid_slices/100

once you download the image
you have to slice it by frames
and display the correct image in the correct time range divided by video length

**Comment by oahmedazab** [comment]
@giladna 

thank you so much for your help

this is the api you're mention above right ?
https://knowledge.kaltura.com/kaltura-thumbnail-api#

**Comment by giladna** [comment]
@oahmedazab  yes.
