### ISSUE TITLE
Unable to compile the new 3.2.0 SDK

### ISSUE THREAD

**Issue by omkarhande-zz** [kaltura/playkit-android#506]
Console o/p:
java.lang.RuntimeException: Android dependency 'com.google.android.gms:play-services-basement' has different version for the compile (11.0.2) and runtime (16.0.1) classpath. You should manually set the same version via DependencyResolution

**Comment by kaltura-hooks** [comment]
Hi @omkarhande,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
hi @omkarhande - thanks for that we're checking...

**Comment by giladna** [comment]
@omkarhand
could you share your gradle?

could you reproduce it on SDK v3.7.1?

**Comment by omkarhande-zz** [comment]
@giladna 

I was able to fix the issue by downgrading the Google Play services gradle plugin to 3.0.0 from 4.1.0 
I am unable to compile with v3.7.1 - throws this errors
`Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.`

**Comment by giladna** [comment]
@omkarhande thanks!
Are you using 3.7.1 for all playkit packages? if not please do

**Comment by omkarhande-zz** [comment]
> @omkarhande thanks!
> Are you using 3.7.1 for all playkit packages? if not please do

This solved it. Thanks!
