### ISSUE TITLE
Expose setresizemode.

### ISSUE THREAD

**Issue by equistar** [kaltura/playkit-android#524]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-android/issues): Yes
- [x] Which Player [version](https://github.com/kaltura/playkit-android/releases) are you using: 3.7.1
- [x] Can you reproduce the issue with our latest release version: Yes
- [x] Can you reproduce the issue with the latest code from master: Yes
- [x] What devices and OS versions are you using: LG V30+ Android 8.0
- [x] If applicable, add test code or test page to reproduce: 
```

```

##### Expected behavior
The SDK should expose the function which is already given by SimpleExoPlayerView. 

i.e simpleExoPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);

##### Actual behavior
There are for modes : 
Resize mode fill
Resize mode fit
Resize mode zoom
Resize mode Fixed

In Device with 18:9 aspect ratio the screen fills with video and remove the size black bars.

**Comment by kaltura-hooks** [comment]
Hi @equistar,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by equistar** [comment]
Hi,

We are using just the kaltura player for Android and are not using any kind of backend service.

**Comment by giladna** [comment]
@equistar 

This feature will be added to our next version v3.8.1

https://github.com/kaltura/playkit-android/pull/527

10x
