### ISSUE TITLE
Please add getVolume for "interface Player" 

### ISSUE THREAD

**Issue by azatserzhan** [kaltura/playkit-android#596]
I know about listener PlayerEvent.volumeChanged. It is doesn't solve my problem.
Thank you friends!

**Comment by giladna** [comment]
hi,

I have checked this again.

unless you set the volume yourself (this API exists)
then there is no point in getVolume since exo player will always return 1.0 to get volume

in case that you call setVolume by the API you will receive the event with the current volume
as long as the value has changed
so for now I am not sure it is required

**Comment by azatserzhan** [comment]
Hi Gilad.
I have two player, one for small size, second for full screen.
Kaltura player included in custom view. When mute sound in one player, I
want automatically mute second kalura player.
For optimize memory I attach only one player. When I attach second kaltura
player volume is correct work, but listener onVolumeChange not working.
Please add getVolume() for interface Player.

**Comment by giladna** [comment]
@azatserzhan  please use the setVolume API

 player.setVolume(0); player.setVolume(1);

when ever you want

once you change it the event will be fired as I wrote

**Comment by azatserzhan** [comment]
1) I am attaching a player for view A and detach in the view B. 
2) Mute video  ( setVolume(0) )
3) When attaching B and detach A, video is mute, but onVolumeChange not working.

**Comment by giladna** [comment]
the event is fired each time the setVolume API is called and the current value is different from the prev one 
this is not working for you?
