### ISSUE TITLE
[Question] add/remove plugins after PlayKitManager.loadPlayer

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android#632]
is there a way to to disable or remove plugins after calling `PlayKitManager.loadPlayer`
i have a list of videos but i don't want all the plugins to be enabled in all videos

instead of creating new player with its plugins for each video, i want to create player once is that possible?

**Comment by GouravSna** [comment]
Hi @oahmedazab ,

There is no way to remove the plugin but there is `player.updatePluginConfig()` where you can pass an updated plugin. Suppose if you don't want to use IMA plugin for the next media. Please pass an empty ad tag in updatePluginConfig.

Yes. Instead of creating a new player, please use a new `PKMediaConfig` object and prepare the player again on the same player object.

**Comment by oahmedazab** [comment]
Yes. i was using this approach to pass empty or null config to plugins that i don't wanna use.
i was just wondering if there is another approach to do it.
Thanks 😄
